In [1]:
import os
import numpy as np
# from nltk.corpus import stopwords
from string import punctuation
from gensim.models import word2vec

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [3]:
np.random.seed(42)

In [4]:
import spacy
nlp = spacy.load("en_core_web_sm")

In [5]:
train_data = "C:\\Users\\user\\OneDrive\\Surgeclass\\word vector text\\train_data.csv"
test_data = "C:\\Users\\user\\OneDrive\\Surgeclass\\word vector text\\test_data_new.csv"

In [6]:
import csv

X = []
y = []

with open(train_data, "r") as infile:
    reader = csv.reader(infile)
    for row in reader:
        if len(row) >= 2:
            label = row[0]
            text = row[1]
            X.append(text.split())
            y.append(label)
print("Total examples: %s" % len(y))


Total examples: 19999


In [7]:
print(X[0])

['labels']


In [8]:
y[2]

'I am not interested in cars or electric appliances .'

In [10]:
import csv
import numpy as np

import csv

X_test = []
y_label = []

with open(test_data, "r") as infile:
    reader = csv.reader(infile)
    for row in reader:
        if len(row) >= 2:
            label = row[0]
            text = row[1]
            X_test.append(text.split())
            y_label.append(label)

print("Total examples: %s" % len(y_label))



Total examples: 10025


In [11]:
print(X_test[0])

['labels']


In [12]:
print(y_label[127])

I study English 


In [13]:
if len(y_test) > 0:
    print(y_test[0])


NameError: name 'y_test' is not defined

In [14]:
import numpy as np

X_array = np.array(X)
X_test_array = np.array(X_test)

X_shape = X_array.shape
X_test_shape = X_test_array.shape

print("Shape of X:", X_shape)
print("Shape of X_test:", X_test_shape)


Shape of X: (19999, 1)
Shape of X_test: (10025, 1)


In [15]:
np.unique(y, return_counts=True)

(array([' ', " ' Cause I believe there is a way you can love me",
        " ' Geso ' means suqid is legs in Japanese .", ...,
        'you might be cryed from some relationships .', 'young answered',
        'your heart might be hurt by thinking own lover too much .'],
       dtype='<U1933'),
 array([75,  1,  1, ...,  1,  1,  1], dtype=int64))

In [16]:
X[0],

(['labels'],)

In [17]:
y[561]

'you can listening on podcast .'

In [18]:
#WORD EMBEDDINGS

In [19]:
import gensim
import gensim.downloader as api
print(list(gensim.downloader.info()['models'].keys()))

['fasttext-wiki-news-subwords-300', 'conceptnet-numberbatch-17-06-300', 'word2vec-ruscorpora-300', 'word2vec-google-news-300', 'glove-wiki-gigaword-50', 'glove-wiki-gigaword-100', 'glove-wiki-gigaword-200', 'glove-wiki-gigaword-300', 'glove-twitter-25', 'glove-twitter-50', 'glove-twitter-100', 'glove-twitter-200', '__testing_word2vec-matrix-synopsis']


In [20]:
import gensim.downloader as api
wv = api.load('glove-twitter-50')
wv.most_similar('happy')

[('birthday', 0.9478021860122681),
 ('day', 0.884091317653656),
 ('love', 0.8704721927642822),
 ('thank', 0.8623553514480591),
 ('wish', 0.8603642582893372),
 ('miss', 0.8560664653778076),
 ('bday', 0.8472115397453308),
 ('merry', 0.8461399078369141),
 ('welcome', 0.8427104949951172),
 ('hope', 0.8396720290184021)]

In [21]:
wv.vector_size

50

In [22]:
import string
stop_words = nlp.Defaults.stop_words
punctuations = string.punctuation

In [23]:
def sent_vec(sent,w2v):
    vector_size = w2v.vector_size
    wv_res = np.zeros(vector_size)
    ctr = 1
    for w in sent:
        if w in w2v:
            ctr += 1
            wv_res += w2v[w]
    wv_res = wv_res/ctr
    return wv_res

In [24]:
sent_vec("I am happy",wv)

array([ 0.11221238,  0.08086875,  0.07783688, -0.038995  , -0.18682502,
        0.17493849, -0.42813626,  0.18419874, -0.13961012, -0.1894935 ,
       -0.18459575, -0.39523976, -2.99103752, -0.0456085 , -0.02529901,
        0.33934125, -0.37086751, -0.10923225, -0.102813  ,  0.85966501,
       -0.24663988, -0.36515624,  0.20198388,  0.03161625,  0.02450538,
       -1.66976251, -0.04163662, -0.0357965 ,  0.26119274,  0.57394749,
        0.04942275, -0.32102951,  0.13673   , -0.03791625,  0.52639925,
        0.50934474, -0.22326875, -0.27457125, -0.59217638,  0.28203475,
       -2.33953753,  0.19693125,  0.2576075 , -0.14676042,  0.259737  ,
        0.10288475, -0.10105875, -0.08618125,  0.12835125, -0.84626376])

In [25]:
print(X[0])

['labels']


In [26]:
train_doc_vecs = []
for doc in X:
    doc_words = [term for term in doc if term not in stop_words]
    train_doc_vecs.append(sent_vec(doc_words,wv))

In [27]:
train_doc_vecs[1]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [28]:
test_doc_vecs = []
for doc in X_test:
    doc_words = [term for term in doc if term not in stop_words]
    test_doc_vecs.append(sent_vec(doc_words,wv))

In [29]:
test_doc_vecs[1]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [30]:
# Building a predictive model on the averaged word vectors

In [31]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [32]:
train_doc_vecs[0]

array([ 0.159095  , -0.192035  , -0.19802   ,  0.42375499,  0.57480001,
       -0.31494501,  0.12931   , -0.35712501,  0.43636   , -0.251625  ,
        0.18810999, -0.0420895 , -1.11535001, -0.25597   , -0.16881999,
        0.00445915, -0.188445  , -0.12794501,  0.70020002,  0.0234885 ,
       -0.367845  , -0.035123  ,  0.00448865, -0.19622999, -0.03782   ,
        0.57539999,  0.359     ,  0.46763   , -0.21997   , -0.28363499,
        0.213165  ,  0.16571499, -0.251845  ,  0.24798   ,  0.28942499,
       -0.5589    , -0.099105  ,  0.23275   ,  0.10925   ,  0.129365  ,
        0.41346499,  0.1009    ,  0.018162  , -0.316645  , -0.112645  ,
       -0.2757    ,  0.12529001, -0.0071815 , -0.232195  , -0.361985  ])

In [33]:
type(train_doc_vecs)

list

In [34]:
logreg = LogisticRegression()
logreg.fit(train_doc_vecs,y)

LogisticRegression()

In [35]:
pred_train_ys = logreg.predict(train_doc_vecs)
pred_test_ys = logreg.predict(test_doc_vecs)
print("Train accuracy: ", accuracy_score(pred_train_ys, y))


Train accuracy:  0.0038001900095004752


In [37]:

#print("Test accuracy: ", accuracy_score(pred_test_ys, x_test))
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_label, pred_test_ys)
print("Test accuracy: ", accuracy)


Test accuracy:  0.0043890274314214465


In [38]:
#Training our own wordvectors on the data

In [40]:
x_comb = np.concatenate([y,y_label])
len(x_comb)

30024

In [41]:
print(x_comb[5])

Fortunately , my older sister is friend is a dentist .


In [42]:
w2v = word2vec.Word2Vec(x_comb, window=2, min_count=2)
w2v

In [43]:
#Getting the sentence vectors for the test and train sets

In [44]:
train_doc_vecs = []
for doc in X:
    doc_words = [term for term in doc if term not in stop_words]
    train_doc_vecs.append(sent_vec(doc_words,w2v.wv))

In [45]:
test_doc_vecs = []
for doc in X_test:
    doc_words = [term for term in doc if term not in stop_words]
    test_doc_vecs.append(sent_vec(doc_words,w2v.wv))

In [46]:
def fit_predict(algo):
  algo.fit(train_doc_vecs,y)
  pred_train_ys = algo.predict(train_doc_vecs)
  pred_test_ys = algo.predict(test_doc_vecs)
  print("Train accuracy: ", accuracy_score(pred_train_ys, y))
  print("Test accuracy: ", accuracy_score(pred_test_ys, y_label))

In [47]:
from sklearn.linear_model import LogisticRegression
algo = LogisticRegression()
fit_predict(algo)

Train accuracy:  0.0037501875093754688
Test accuracy:  0.00428927680798005


In [48]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
fit_predict(rf)

Train accuracy:  0.0037501875093754688
Test accuracy:  0.00428927680798005
